### ISSUE TITLE
trouble with vcloud-launch

### ISSUE THREAD

**Issue by Azulinho** [gds-operations/vcloud-tools#151]
Hey!

I am using vcloud-rest through some code I cooked to build VAPPs on my vcloud org through a VAPP template.
https://github.com/dvla/vcloud-management-tools, I am able to use that vcloud-rest library without any issues to login to vcloud director and do what I need.

As I also use ansible to apply config code into my nodes, I was keen to use your vcloud-tools and define my vcloud boxes from a yaml file.

However when frying up your latest code I always get very odd flavours, have you tasted this one before?

```
\> bundle exec vcloud-launch test.yaml 
/home/azul/.rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/forwardable.rb:204: stack level too deep (SystemStackError)
```

my test.yaml file:

```

---
vapps:
 -  name: 'vapp-example-1'
    vdc_name: '00000000-0000-0000-0000-000000000000'
    catalog: 'MyCatalog'
    catalog_item: 'MyTemplate-1501'
```

my ~/.fog

```
default:
    vcloud_director_username: '000.00.00000'
    vcloud_director_password: 'password'
    vcloud_director_host: 'api.vcd.portal.skyscapecloud.com'
```

any clue?
