### ISSUE TITLE
-bash: I, Command Not Found

### ISSUE THREAD

**Issue by vialde** [gds-operations/vcloud-tools#204]
Some oddness here as well.  Trying to launch servers with the following

```
eval $(FOG_CREDENTIAL=vcloud_creds vcloud-launch git/gitlab/yaml/skyscape.yaml)
```

Yields this

```
-bash: I,: command not found
```

My yaml file is 

``` yaml
vapps:
  - name: 'app0001-01'
    vdc_name: 'XXXXX'
    catalog_name: 'PaaS catalog'
    vapp_template_name: 'Red Hat Enterprise Linus 6 64-bit'
    vm:
      hardware_config:
        memory: 2048
        cpu: 2
      network_connections:
      - name: 'collaboration'
        ip_address: 'XXXXX'
      metadata:
        role: XXXX
        environment: Development
      storage_profile: '40-60-6-BASIC-Any'
```

Any Ideas?
